Refactoring javascript code with classes and class methods
gisachris/AwesomeBooks pull request #2
Opened 2023-05-02 15:58 UTC by gisachris

##PR

- Add CSS for the wireframe UI for the Awesome Books project.
- Added box-shadow for the remove button.
- Aligned items at the center to match the given UI.

2023-05-02 17:41 UTC, KDlamini requested changes
### Hi @gisachris, @SiveMdluli  🙋‍♀️,  

Great work so far! 💯 
You have done a great job creating a working Awesome Books application using classes 🎊 🥳 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  Javascript class is used to add all functionalities
✔️  addBook and removeBook functions are created inside the class

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 17:41 UTC, KDlamini commented on index.html
You have a broken logo link on your README. Please make sure that you do not have any broken links on your README to ensure professionalism.

![image](https://user-images.githubusercontent.com/38088818/235729412-2105f8a2-d969-47df-9d81-5509f0d45d47.png)

- I noticed that you referenced a `port.PNG` file in the `images` directory that does not exist in your repository. Kindly add the logo file to your project OR otherwise remove the logo element in your README.

The same thing applies to the broken `issues` link. 

- Kindly add a working URL to your issues page in order for users to be able to redirect to the project issues.

2023-05-02 17:41 UTC, KDlamini commented on index.html
## [OPTIONAL]

You have done a great job in refactoring your code to use JavaScript classes. 👏🏾 🥳 
There's a way you can improve your code to optimize your class and reduce the amount of code in your file:

- Store books in the constructor method instead of having a variable.

```javascript
  constructor() {
    this.books = [];
  }
```

-  Create methods for fetching and saving to storage.

```javascript
  saveToStorage() {
    localStorage.setItem('storedBooks', JSON.stringify(this.books));
  }

  getFromStorage() {
    return JSON.parse(localStorage.getItem('storedBooks'));
  }
```

- Create `getBooks()` and `removeBooks()` like this.

```javascript
  addBook(title, author) {
    this.books = this.books.concat({ title, author });
    saveToStorage() // This will automatically get the new books state and save it to localStorage
  }

  removeBook(id) {
    this.books = this.books.filter(({ title }) => title !== id); 
    saveToStorage() // This will automatically get the new books state and save it to localStorage
  }
```

- Set a getter method to fetch all books in the class.

 ```javascript
  getBooks() {
    return this.books;
  }
```

Notice how I did not use the `function` keyword when declaring the functions. That's because the ES6 syntax for declaring methods inside classes does not require the `function` keyword. 
I hope this helps become an even better programmer.

2023-05-02 17:41 UTC, KDlamini commented on index.html
in `app.js` line 111, kindly remove the commented code that you are not using to clean up your code.

![image](https://user-images.githubusercontent.com/38088818/235740445-f0518ef4-c69c-4ea4-94bc-fe1eeb0557ac.png)

2023-05-02 17:41 UTC, KDlamini commented on index.html
Please do not disable linters because they are meant to help you follow the best practices.

![image](https://user-images.githubusercontent.com/38088818/235740832-96422b80-7337-47a5-96aa-6471de0ae106.png)

- I see the `no-use-before-define` rule is because you used the `display()` method before the function was created. You can simply move the if statement and put it below the `display` method declaration to fix this issue.
- For now, disabling the `no-plusplus` is okay ✔️. There's no other way to avoid `i++` when using `for` loops.

2023-05-03 11:24 UTC, SiveMdluli commented
##PR Comment
Fixed suggested changes:
- Fix broken links
- Added image logo for the readme.md file
- Had a collaboration session

2023-05-03 11:49 UTC, LionRouge1 approved these changes
Hi @gisachris and @SiveMdluli, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-05-03 16:10 UTC, merged